### ISSUE TITLE
Support LDAP authentication

### ISSUE THREAD

**Issue by stevenroose** [YunoHost-Apps/wallabag_ynh#11]
This depends on wallabag/wallabag#966, which is planned for Wallabag v2.

Would also fix #6

**Comment by jeromelebleu** [comment]
As described in the [README](https://github.com/YunoHost-Apps/wallabag_ynh#future), the migration is not user-intervention-free... That's why we suggest to make a new application for v2, in the hope that LDAP support will be added soon! Meanwhile, I'll close your request. Feel free to re-open in the upcoming new YunoHost app package for Wallabag v2!
